# See https://circleci.com/docs/2.0/language-ruby/ for more details

version: 2.1

orbs:
  ruby: circleci/ruby@2.0.1

jobs:
  checks:
    parallelism: 1
    resource_class: small
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - checkout
      - ruby/install-deps:
          key: gems-v2
          include-branch-in-cache-key: false
      # - ruby/rubocop-check
      - run:
          name: RSpec Tests
          command: |-
            bundle exec rspec --format RspecJunitFormatter \
              --out /tmp/test-results/rspec/results.xml --format progress

workflows:
  version: 2
  checks:
    jobs:
      - checks
